WebApplicationCaisseEnregistreuse/Models/Categorie.cs
namespace WebApplicationCaisseEnregistreuse.Models
{
    public class Categorie
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public List<Produit> ListeProduits { get; set; }
    }
}

WebApplicationCaisseEnregistreuse/Models/ErrorViewModel.cs
namespace WebApplicationCaisseEnregistreuse.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationCaisseEnregistreuse/Models/Produit.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationCaisseEnregistreuse.Models
{
    public class Produit
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Le nom est requis")]
        public string Nom { get; set; }

        [Required(ErrorMessage = "La description est requise")]
        public string Description { get; set; }

      //  [Range(0.01, double.MaxValue, ErrorMessage = "Le prix doit être supérieur à zéro")]
        public decimal Prix { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "La quantité en stock doit être un nombre positif")]
        public int QuantiteStock { get; set; }

        [Required(ErrorMessage = "La catégorie est requise")]
        public string Categorie { get; set; }

        public string ImageUrl { get; set; }
    }
}

WebApplicationCaisseEnregistreuse/Controllers/CategorieController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplicationCaisseEnregistreuse.Models;
using WebApplicationCaisseEnregistreuse.Repository;

namespace WebApplicationCaisseEnregistreuse.Controllers
{
    public class CategorieController : Controller
    {
        private readonly CategorieRepository _categorieFromDb;

        public CategorieController(CategorieRepository CategorieFromDb)
        {
            _categorieFromDb = CategorieFromDb;
        }


        public IActionResult Index()
        {
            return View(_categorieFromDb.GetAll());
        }

        public IActionResult Add(Categorie aCategorie)
        {
            _categorieFromDb.Add(aCategorie);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteByID(int id)
        {

            Categorie? CategorieToDelete = _categorieFromDb.GetById(id);

            if (CategorieToDelete == null)
                return RedirectToAction(nameof(Index));


            _categorieFromDb.DeleteByID(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

WebApplicationCaisseEnregistreuse/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplicationCaisseEnregistreuse.Models;

namespace WebApplicationCaisseEnregistreuse.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationCaisseEnregistreuse/Controllers/ProduitController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationCaisseEnregistreuse.Models;
using WebApplicationCaisseEnregistreuse.Repository;

namespace WebApplicationCaisseEnregistreuse.Controllers
{
    public class ProduitController : Controller
    {
        private readonly ProduitRepository _produitFromDb;

        public ProduitController(ProduitRepository ProduitFromDb)
        {
            _produitFromDb = ProduitFromDb;
        }


        public IActionResult Index()
        {
            return View(_produitFromDb.GetAll());
        }

        public IActionResult Details(int id)
        {

            Produit? ProduitDetails = _produitFromDb.GetById(id);
            return View(ProduitDetails);
        }

        public IActionResult Add(int id)
        {
            if (id == 0) 
                return View();

            var produit = _produitFromDb.GetById(id);
            return View(produit);
        }



        public IActionResult DeleteByID(int id)
        {

            Produit? ProduitToDelete = _produitFromDb.GetById(id);

            if (ProduitToDelete == null)
                return RedirectToAction(nameof(Index));


            _produitFromDb.DeleteByID(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

WebApplicationCaisseEnregistreuse/Views/Categorie/Index.cshtml
@model List<Categorie>
@{

}

<br>
<h1>Liste des produits</h1>
<br>
<br>
<br>

        public int Id { get; set; }
        public string Nom { get; set; }
        public List<Produit>
    ListeProduits { get; set; }

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">@Html.DisplayNameForInnerType((Categorie m) => m.Nom)</th>
          @*  <th scope="col">@Html.DisplayNameForInnerType((Categorie m) => m.ListeProduits)</th> *@
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Categorie m in Model)
        {
            <tr>
                <th scope="row">@m.Id</th>
                <td>@m.Nom</td>
                 @*    <td>@m.ListeProduits</td> *@
                <td><a class="btn btn-outline-danger btn-danger btn-delete" asp-action="DeleteByID" asp-route-id="@m.Id">X</a></td>
            </tr>
        }
    </tbody>
</table>

WebApplicationCaisseEnregistreuse/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationCaisseEnregistreuse/Views/Produit/Add.cshtml
@model Produit
@{
    bool isUpdate = Model != null;
    ViewData["Title"] = (isUpdate ? "Modifier" : "Ajouter") + " un Produit";
}

<h1>@(isUpdate ? "Modifier" : "Ajouter")</h1>

<form asp-action="Add" enctype="multipart/form-data">
   

    <input asp-for="Id" type="hidden" class="form-control">
  

    <div class="mb-3">
        <label asp-for="Nom" class="form-label"></label>
        <input asp-for="Nom" type="text" class="form-control">
        <span asp-validation-for="Nom" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" type="text" class="form-control">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Categorie" class="form-label"></label>
        <input asp-for="Categorie" type="text" class="form-control">
        <span asp-validation-for="Categorie" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Prix" class="form-label"></label>
        <input asp-for="Prix" type="number" class="form-control">
        <span asp-validation-for="Prix" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="QuantiteStock" class="form-label"></label>
        <input asp-for="QuantiteStock" type="number" class="form-control">
        <span asp-validation-for="QuantiteStock" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label">Photo du Produit</label>
        <input type="file" name="picture">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

  @*   <div class="text-danger">@Html.ValidationSummary()</div> *@
</form>

@* 
    @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} 
    *@

WebApplicationCaisseEnregistreuse/Views/Produit/Details.cshtml
@model Produit
@{
    Layout = null;
}
@{
    ViewData["Title"] = "En savoir plus";
    Produit produit = Model;
}
<body>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
        }

        .card {
            max-width: 20rem;
            width: 100%;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            background-color: #ffffff; 
            border-radius: 15px;
            overflow: hidden;
        }

        .card-img-top {
            width: 100%;
            height: 250px;
            object-fit: cover; 
            border-top-left-radius: 15px;
            border-top-right-radius: 15px;
        }

        .card-body {
            padding: 20px;
            text-align: center;
        }



        .card-link {
            color: #007B5E; 
            text-decoration: none;
            font-weight: bold;
            display: inline-block;
            margin-top: 15px;
            padding: 10px 20px;
            border: 1px solid #007B5E; 
            border-radius: 5px;
            transition: background-color 0.3s;
        }

            .card-link:hover {
                background-color: #007B5E; 
                color: #fff; 
            }

        ul {
            list-style-type: none;
        }
    </style>

    @if (produit != null)
    {
        <div class="card">
            <img src="" class="card-img-top" alt=" Image">
            <div class="card-body">
                <h7 class="card-title" style="font-size: 25px;">@produit.Nom</h7>
            </div>
            <ul style="line-height: 1.5;">
                <li class="list-group-item ">@produit.QuantiteStock en entrepôt</li>
                <li class="list-group-item">@produit.Prix €</li>
                <li class="list-group-item"> @produit.Description </li>
                <li class="list-group-item"> @produit.Categorie </li>
            </ul>
            <div class="card-body">
                <a asp-action="Index" class="card-link">Retour à la liste</a>
            </div>
        </div>
    }

</body>

WebApplicationCaisseEnregistreuse/Views/Produit/Index.cshtml
@model List<Produit>
@{

}


<br>
<h1>Liste des produits</h1>
<br>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">@Html.DisplayNameForInnerType((Produit m) => m.Nom)</th>
            <th scope="col">@Html.DisplayNameForInnerType((Produit m) => m.Description)</th>
            <th scope="col">@Html.DisplayNameForInnerType((Produit m) => m.Prix)</th>
            <th scope="col">Quantite</th>
            <th scope="col">@Html.DisplayNameForInnerType((Produit m) => m.Categorie)</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Produit m in Model)
        {
            <tr>
                <th scope="row">@m.Id</th>
                <td>@m.Nom</td>
                <td>@m.Description</td>
                <td>@m.Prix</td>
                <td>@m.QuantiteStock</td>
                <td>@m.Categorie</td>
                <td><a class="btn btn-outline-light btn-details" asp-action="AddPanier" asp-route-id="@m.Id">+</a></td>
                <td><a class="btn btn-outline-light btn-details" asp-action="Details" asp-route-id="@m.Id">Details</a></td>
                <td><a class="btn btn-outline-light btn-details" asp-action="Add" asp-route-id="@m.Id">Modifier</a></td>
                <td><a class="btn btn-outline-danger btn-danger btn-delete" asp-action="DeleteByID" asp-route-id="@m.Id">X</a></td>
            </tr>
        }
    </tbody>
</table>


@* 
<div>
    <br><br><br>
    <section>

        <form id="rechercheForm" method="get" action="/Task/Add">
            <h1>Nouveau produit</h1>

            <div class="mb-3">
                <label for="Title" class="form-label">Title :</label>
                <input type="text" class="form-control" id="Title" name="Title">
                <span class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Poids" class="form-label">Description :</label>
                <input type="text" class="form-control" id="Description" name="Description">
            </div>
            <div class="text-danger">@Html.ValidationSummary()</div>

            <label for="id"></label>
            <button class="btn btnoutline-light btn-details text-white" type="submit">Create</button>
        </form>
    </section>
    <br>

</div> *@

WebApplicationCaisseEnregistreuse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationCaisseEnregistreuse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationCaisseEnregistreuse.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark btn-details border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">La Caisse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produit" asp-action="Index">Produit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produit" asp-action="Add">Ajouter un Produit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categorie" asp-action="Index">Categorie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categorie" asp-action="Index">Ajouter une Categorie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categorie" asp-action="Index">Produit d'une Categorie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Panier">Panier</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>